import flet as ft

TEXT_FAMILY = "BRLNSR"

text_theme = ft.TextTheme(
    body_small=ft.TextStyle(
        size=12,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    body_medium=ft.TextStyle(
        size=14,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    body_large=ft.TextStyle(
        size=18,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    display_small=ft.TextStyle(
        size=14,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    display_medium=ft.TextStyle(
        size=18,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    display_large=ft.TextStyle(
        size=24,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    headline_small=ft.TextStyle(
        size=18,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_800,
    ),
    headline_medium=ft.TextStyle(
        size=24,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_800,
    ),
    headline_large=ft.TextStyle(
        size=48,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_800,
    ),
    label_small=ft.TextStyle(
        size=14,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    label_medium=ft.TextStyle(
        size=18,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    label_large=ft.TextStyle(
        size=24,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_300,
    ),
    title_small=ft.TextStyle(
        size=24,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_500,
    ),
    title_medium=ft.TextStyle(
        size=36,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_500,
    ),
    title_large=ft.TextStyle(
        size=48,
        font_family=TEXT_FAMILY,
        weight=ft.FontWeight.W_500,
    ),
)
